name: Deploy react app

on: 
  push: 
    branches: 
      - main
  workflow_dispatch:

jobs:
  build_e_deply_react_app:
    runs-on: ubuntu-latest
    steps:
      - name: Mudando para repositório 
        uses: actions/checkout@v3
      
      - name: Entrando na pasta raiz do react app
        run: cd devops-test-app

      - name: Checando working directory e arquivos
        run: |
          pwd
          ls -la