name: Deploy react app

on: 
  push: 
    branches: 
      - main
  workflow_dispatch:

jobs:
  build_e_deply_react_app:
    runs-on: ubuntu-latest
    steps:
      - name: Adicionando arquivos do repositório 
        uses: actions/checkout@v3
      
      - name: Instalando dependencias
        run: |
          cd devops-test-app
          npm install

      - name: Building app
        run: |
        cd devops-test-app
        npm run build

      - name: Realizando deployment para github pages
        run: cd devops-test-app/build
        uses: peaceiris/actions-gh-pages@v3