name: Deploy react app

on: 
  push: 
    branches: 
      - main
  workflow_dispatch:

jobs:
  build_e_deply_react_app:
    runs-on: ubuntu-latest
    steps:
      - name: Mudando para repositório 
        uses: actions/checkout@v3
      
      - name: Instalando dependencias
        run: |
          cd devops-test-app
          npm install

      - name: Iniciando aplicação
        run: |
          cd devops-test-app
          npm start